version: '3.9' #2.1'
services:
  webservice:
    container_name: webservice
    hostname: webservice
    build: ./app
    image: liquid-webapp:latest
    ports:
      - "8080:8080"
      - "8081:5000"
      - "22:22"
    environment:
      - "FLASK_PORT=8080"
    cap_add:
      - NET_ADMIN
      - SYS_ADMIN
    stdin_open: false
    tty: false
    networks:
      appnet:
        ipv4_address: 172.7.0.7

  master:
    container_name: master
    hostname: master
    build: ./clients
    image: liquid-clients
    volumes:
      - ./clients:/opt/clients
    stdin_open: true # docker run -i
    tty: true        # docker run -t
    networks:
      appnet:
        ipv4_address: 172.7.0.8

  enemy:
    container_name: enemy
    hostname: enemy
    build: ./clients
    image: liquid-clients
    stdin_open: true # docker run -i
    tty: true        # docker run -t
    networks:
      appnet:
        ipv4_address: 172.7.0.9
        
networks:
  appnet:
      driver: bridge
      ipam:
          driver: default
          config:
              - subnet: "172.7.0.0/16"
